# Generated by Django 4.2 on 2025-03-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority_value',
            field=models.IntegerField(default=3),
        ),
    ]
